import type { Job } from "@/types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Growth Marketing Manager",
    company: "TechScale",
    companyLogo: "/companies/techscale.svg",
    location: "San Francisco, CA",
    workLocation: "Hybrid",
    salary: { min: 140000, max: 180000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Senior",
    description:
      "We're looking for a Senior Growth Marketing Manager to lead our demand generation efforts and scale our B2B SaaS marketing engine. You'll work closely with sales, product, and leadership to drive pipeline growth.",
    responsibilities: [
      "Develop and execute multi-channel demand generation campaigns",
      "Own marketing qualified lead (MQL) targets and conversion optimization",
      "Build and manage paid acquisition channels (Google, LinkedIn, etc.)",
      "Create compelling content and messaging for target personas",
      "Analyze campaign performance and optimize for ROI",
      "Collaborate with sales on lead scoring and handoff processes",
    ],
    requirements: [
      "5+ years of B2B SaaS marketing experience",
      "Proven track record of scaling demand generation programs",
      "Experience with marketing automation tools (HubSpot, Marketo)",
      "Strong analytical skills and data-driven mindset",
      "Excellent written and verbal communication skills",
    ],
    benefits: [
      "Competitive salary and equity",
      "Health, dental, and vision insurance",
      "Flexible PTO policy",
      "Remote work flexibility",
      "Learning and development budget",
    ],
    tags: ["Marketing", "B2B", "SaaS", "Growth", "Demand Gen"],
    postedAt: new Date("2025-01-28"),
    isUrgent: true,
    isFeatured: true,
    applicationUrl: "https://techscale.com/careers/growth-marketing",
  },
  {
    id: "2",
    title: "Account Executive - Mid-Market",
    company: "CloudSync",
    companyLogo: "/companies/cloudsync.svg",
    location: "New York, NY",
    workLocation: "Remote",
    salary: { min: 120000, max: 150000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Mid",
    description:
      "Join our fast-growing sales team as an Account Executive focused on mid-market accounts. You'll manage the full sales cycle from prospecting to close, working with companies in the $10M-$500M revenue range.",
    responsibilities: [
      "Manage full-cycle sales from prospecting to close",
      "Build and maintain a healthy sales pipeline",
      "Conduct product demos and discovery calls",
      "Negotiate contracts and pricing",
      "Collaborate with SDRs and customer success",
      "Achieve and exceed quarterly quotas",
    ],
    requirements: [
      "3-5 years of B2B SaaS sales experience",
      "Track record of meeting/exceeding quota",
      "Experience with CRM tools (Salesforce preferred)",
      "Strong presentation and negotiation skills",
      "Self-motivated with excellent time management",
    ],
    benefits: [
      "Competitive base + uncapped commission",
      "Stock options",
      "Health benefits",
      "401(k) matching",
      "Sales club trips",
    ],
    tags: ["Sales", "B2B", "SaaS", "Mid-Market", "Account Executive"],
    postedAt: new Date("2025-01-27"),
    isFeatured: true,
    applicationUrl: "https://cloudsync.com/careers/ae-midmarket",
  },
  {
    id: "3",
    title: "Product Marketing Manager",
    company: "DataFlow",
    location: "Austin, TX",
    workLocation: "Hybrid",
    salary: { min: 110000, max: 140000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Mid",
    description:
      "We're seeking a Product Marketing Manager to own go-to-market strategy for our data integration platform. You'll be the voice of the customer and bridge the gap between product and sales.",
    responsibilities: [
      "Develop positioning, messaging, and competitive differentiation",
      "Create sales enablement materials and battle cards",
      "Launch new products and features to market",
      "Conduct customer and market research",
      "Train sales team on product value propositions",
      "Analyze win/loss data to inform strategy",
    ],
    requirements: [
      "3+ years of B2B product marketing experience",
      "Experience in data/analytics or developer tools space",
      "Strong storytelling and copywriting skills",
      "Ability to translate technical features into business value",
      "Experience working cross-functionally",
    ],
    benefits: [
      "Competitive compensation",
      "Equity participation",
      "Comprehensive health coverage",
      "Flexible work arrangements",
      "Professional development stipend",
    ],
    tags: ["Product Marketing", "B2B", "Data", "GTM", "SaaS"],
    postedAt: new Date("2025-01-26"),
    applicationUrl: "https://dataflow.io/careers/pmm",
  },
  {
    id: "4",
    title: "Sales Development Representative",
    company: "RevOps Pro",
    location: "Chicago, IL",
    workLocation: "On-site",
    salary: { min: 55000, max: 70000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Entry",
    description:
      "Start your B2B sales career as an SDR at RevOps Pro. You'll be responsible for outbound prospecting, qualifying leads, and setting meetings for our Account Executive team.",
    responsibilities: [
      "Conduct outbound prospecting via email, phone, and LinkedIn",
      "Qualify inbound leads and route to appropriate AEs",
      "Schedule meetings and demos for the sales team",
      "Maintain accurate records in Salesforce",
      "Meet daily and weekly activity metrics",
      "Collaborate with marketing on campaigns",
    ],
    requirements: [
      "Bachelor's degree or equivalent experience",
      "Excellent communication skills",
      "High energy and coachable attitude",
      "Interest in B2B SaaS and technology",
      "Previous internship or customer-facing experience preferred",
    ],
    benefits: [
      "Base salary + commission",
      "Clear promotion path to AE",
      "Health benefits",
      "In-office perks",
      "Sales training program",
    ],
    tags: ["SDR", "Sales", "Entry Level", "B2B", "SaaS"],
    postedAt: new Date("2025-01-25"),
    applicationUrl: "https://revopspro.com/careers/sdr",
  },
  {
    id: "5",
    title: "VP of Sales",
    company: "ScaleUp HQ",
    location: "Boston, MA",
    workLocation: "Hybrid",
    salary: { min: 250000, max: 350000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Executive",
    description:
      "Lead our sales organization as VP of Sales. You'll build and scale the team, develop sales strategy, and own revenue targets as we grow from $10M to $50M ARR.",
    responsibilities: [
      "Build and lead a high-performing sales team",
      "Develop and execute sales strategy and playbooks",
      "Own revenue targets and forecasting accuracy",
      "Establish sales processes and methodologies",
      "Partner with marketing on demand generation",
      "Report to CEO on sales performance and strategy",
    ],
    requirements: [
      "10+ years of B2B SaaS sales experience",
      "5+ years of sales leadership experience",
      "Track record of scaling teams from $10M to $50M+",
      "Experience building sales teams and processes",
      "Strong executive presence and communication",
      "Data-driven approach to sales management",
    ],
    benefits: [
      "Competitive base + significant variable",
      "Meaningful equity stake",
      "Executive benefits package",
      "Board exposure",
      "Shape company growth trajectory",
    ],
    tags: ["VP Sales", "Leadership", "Executive", "B2B", "SaaS"],
    postedAt: new Date("2025-01-24"),
    isFeatured: true,
    applicationUrl: "https://scaleuphq.com/careers/vp-sales",
  },
  {
    id: "6",
    title: "Customer Success Manager",
    company: "RetentionAI",
    location: "Denver, CO",
    workLocation: "Remote",
    salary: { min: 85000, max: 110000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Mid",
    description:
      "Own customer relationships and drive retention as a Customer Success Manager. You'll work with a portfolio of mid-market accounts to ensure adoption, expansion, and renewal.",
    responsibilities: [
      "Manage a portfolio of 40-50 mid-market accounts",
      "Drive product adoption and customer health",
      "Conduct quarterly business reviews",
      "Identify and close expansion opportunities",
      "Manage renewals and mitigate churn risk",
      "Advocate for customers internally",
    ],
    requirements: [
      "3+ years of customer success or account management experience",
      "B2B SaaS experience required",
      "Strong relationship-building skills",
      "Analytical mindset with attention to metrics",
      "Experience with CS tools (Gainsight, ChurnZero)",
    ],
    benefits: [
      "Competitive salary + bonus",
      "Full remote flexibility",
      "Health and wellness benefits",
      "Professional development",
      "Stock options",
    ],
    tags: ["Customer Success", "B2B", "SaaS", "Remote", "Mid-Market"],
    postedAt: new Date("2025-01-23"),
    applicationUrl: "https://retentionai.com/careers/csm",
  },
  {
    id: "7",
    title: "Content Marketing Specialist",
    company: "GrowthEngine",
    location: "Seattle, WA",
    workLocation: "Remote",
    salary: { min: 70000, max: 90000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Entry",
    description:
      "Create compelling content that drives awareness and pipeline for our B2B SaaS platform. You'll produce blog posts, ebooks, case studies, and social content.",
    responsibilities: [
      "Write blog posts, whitepapers, and ebooks",
      "Develop customer case studies and testimonials",
      "Manage social media content calendar",
      "Optimize content for SEO",
      "Collaborate with demand gen on gated content",
      "Track content performance metrics",
    ],
    requirements: [
      "1-3 years of B2B content marketing experience",
      "Excellent writing and editing skills",
      "Understanding of SEO best practices",
      "Experience with CMS platforms (WordPress, etc.)",
      "Portfolio of B2B writing samples",
    ],
    benefits: [
      "Competitive salary",
      "Remote-first culture",
      "Health benefits",
      "Learning budget",
      "Flexible hours",
    ],
    tags: ["Content Marketing", "Writing", "B2B", "SaaS", "Remote"],
    postedAt: new Date("2025-01-22"),
    applicationUrl: "https://growthengine.io/careers/content",
  },
  {
    id: "8",
    title: "Revenue Operations Analyst",
    company: "SalesStack",
    location: "San Francisco, CA",
    workLocation: "Hybrid",
    salary: { min: 95000, max: 120000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Mid",
    description:
      "Join our RevOps team to drive operational excellence across sales, marketing, and customer success. You'll be responsible for analytics, process optimization, and systems administration.",
    responsibilities: [
      "Build and maintain Salesforce reports and dashboards",
      "Analyze funnel metrics and identify optimization opportunities",
      "Own territory planning and quota setting process",
      "Manage sales tech stack integrations",
      "Support forecasting and pipeline reviews",
      "Document and improve sales processes",
    ],
    requirements: [
      "2-4 years of sales/revenue operations experience",
      "Salesforce admin certification preferred",
      "Advanced Excel/Google Sheets skills",
      "Experience with BI tools (Tableau, Looker)",
      "Strong analytical and problem-solving skills",
    ],
    benefits: [
      "Competitive compensation",
      "Equity options",
      "Health, dental, vision",
      "401(k) with matching",
      "Commuter benefits",
    ],
    tags: ["RevOps", "Analytics", "Salesforce", "B2B", "SaaS"],
    postedAt: new Date("2025-01-21"),
    applicationUrl: "https://salesstack.com/careers/revops-analyst",
  },
  {
    id: "9",
    title: "Marketing Operations Manager",
    company: "LeadGen Labs",
    location: "Miami, FL",
    workLocation: "Remote",
    salary: { min: 100000, max: 130000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Senior",
    description:
      "Own our marketing technology stack and operations as Marketing Operations Manager. You'll ensure our marketing engine runs efficiently and drives measurable results.",
    responsibilities: [
      "Manage marketing automation platform (HubSpot/Marketo)",
      "Build and optimize lead scoring and routing",
      "Create marketing attribution models",
      "Maintain data quality and integrations",
      "Support campaign execution and tracking",
      "Report on marketing performance metrics",
    ],
    requirements: [
      "5+ years of marketing operations experience",
      "Expert-level HubSpot or Marketo certification",
      "Experience with Salesforce integration",
      "Strong understanding of B2B buyer journey",
      "SQL and data analysis skills",
    ],
    benefits: [
      "Competitive salary",
      "Remote work",
      "Health benefits",
      "Stock options",
      "Conference budget",
    ],
    tags: ["Marketing Ops", "HubSpot", "B2B", "SaaS", "Remote"],
    postedAt: new Date("2025-01-20"),
    isUrgent: true,
    applicationUrl: "https://leadgenlabs.com/careers/mops",
  },
  {
    id: "10",
    title: "Partnership Manager",
    company: "IntegrateNow",
    location: "Portland, OR",
    workLocation: "Hybrid",
    salary: { min: 110000, max: 140000, currency: "USD", period: "yearly" },
    jobType: "Full-time",
    experienceLevel: "Mid",
    description:
      "Build and manage strategic partnerships to drive co-marketing and co-selling opportunities. You'll identify, recruit, and enable partners to expand our go-to-market reach.",
    responsibilities: [
      "Identify and recruit strategic partners",
      "Develop partner program and enablement materials",
      "Drive co-marketing initiatives with partners",
      "Support partner-sourced deal registration",
      "Manage partner relationships and QBRs",
      "Track and report on partner-influenced revenue",
    ],
    requirements: [
      "3-5 years of partnership or business development experience",
      "B2B SaaS industry experience",
      "Strong relationship-building skills",
      "Experience with partner programs and ecosystems",
      "Excellent presentation skills",
    ],
    benefits: [
      "Competitive base + partner bonus",
      "Equity participation",
      "Health benefits",
      "Flexible PTO",
      "Travel opportunities",
    ],
    tags: ["Partnerships", "Business Development", "B2B", "SaaS", "GTM"],
    postedAt: new Date("2025-01-19"),
    applicationUrl: "https://integratenow.io/careers/partnerships",
  },
];

export function getAllJobs(): Job[] {
  return mockJobs;
}

export function getJobById(id: string): Job | undefined {
  return mockJobs.find((job) => job.id === id);
}

export function getUniqueCompanies(): string[] {
  return [...new Set(mockJobs.map((job) => job.company))];
}
