import { Tool } from "@/types";

export const mockTools: Tool[] = [
  {
    id: "1",
    name: "HubSpot",
    slug: "hubspot",
    description: "All-in-one CRM, marketing, sales, and service platform",
    logo: "/tools/hubspot.svg",
    website: "https://hubspot.com",
    category: ["CRM", "Marketing Automation", "Sales"],
    pricing: "freemium",
    pricingDetails: "Free tier available, paid plans from $45/month",
    integrations: ["Salesforce", "Slack", "Gmail", "Zapier"],
    features: ["Email Marketing", "Lead Scoring", "Sales Pipeline", "Analytics"],
    stats: {
      usageCount: 45,
      winRate: 67,
      avgRating: 4.5,
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "2",
    name: "Mixpanel",
    slug: "mixpanel",
    description: "Product analytics platform for tracking user behavior",
    website: "https://mixpanel.com",
    category: ["Analytics", "Product Analytics"],
    pricing: "freemium",
    pricingDetails: "Free up to 20M events/month, paid from $20/month",
    integrations: ["Segment", "Amplitude", "Data Warehouses"],
    features: ["Event Tracking", "Funnel Analysis", "Retention", "A/B Testing"],
    stats: {
      usageCount: 38,
      winRate: 72,
      avgRating: 4.6,
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2025-01-10"),
  },
  {
    id: "3",
    name: "Gong",
    slug: "gong",
    description: "Revenue intelligence platform analyzing customer interactions",
    website: "https://gong.io",
    category: ["Sales Intelligence", "Conversation Analytics"],
    pricing: "paid",
    pricingDetails: "Custom pricing based on team size",
    integrations: ["Salesforce", "Zoom", "Microsoft Teams"],
    features: ["Call Recording", "Deal Intelligence", "Coaching", "Forecasting"],
    stats: {
      usageCount: 28,
      winRate: 81,
      avgRating: 4.8,
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2025-01-18"),
  },
];
